### ISSUE TITLE
build.sh: E CM67 Can't find music ./musics/d_read_m.wad

### ISSUE THREAD

**Issue by mmaulwurff** [fragglet/miniwad#8]
Running build.sh results in the following output:

[deutex.log](https://github.com/fragglet/miniwad/files/3343070/deutex.log)

commit f9e28ab32b2b6
DeuTex 4.4.902

Am I doing something wrong?

**Comment by fragglet** [comment]
Please upgrade to deutex 5.x:

https://github.com/Doom-Utils/deutex
